-- CreateTable
CREATE TABLE "Compose" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "codeId" INTEGER,
    "gauzeball" TEXT NOT NULL,
    "gauzeballCount" INTEGER NOT NULL,
    "adhesivestrip" TEXT NOT NULL,
    "adhesivestripCount" INTEGER NOT NULL,
    "bandage" TEXT NOT NULL,
    "bandageCount" INTEGER NOT NULL,
    "clip" TEXT NOT NULL,
    "clipCount" INTEGER NOT NULL,
    "coating" TEXT NOT NULL,
    "coatingCount" INTEGER NOT NULL,
    "container" TEXT NOT NULL,
    "containerCount" INTEGER NOT NULL,
    "gauzepad" TEXT NOT NULL,
    "gauzepadCount" INTEGER NOT NULL,
    "needleholder" TEXT NOT NULL,
    "needleholderCount" INTEGER NOT NULL,
    "pintset" TEXT NOT NULL,
    "pintsetCount" INTEGER NOT NULL,
    "plasterfixed" TEXT NOT NULL,
    "plasterfixedCount" INTEGER NOT NULL,
    "plastermain" TEXT NOT NULL,
    "plastermainCount" INTEGER NOT NULL,
    "plasterwith" TEXT NOT NULL,
    "plasterwithCount" INTEGER NOT NULL,
    "scalpel" TEXT NOT NULL,
    "scalpelCount" INTEGER NOT NULL,
    "scalpelsharptip" TEXT NOT NULL,
    "scalpelsharptipCount" INTEGER NOT NULL,
    "tweezers" TEXT NOT NULL,
    "tweezersCount" INTEGER NOT NULL,
    "withaperture" TEXT NOT NULL,
    "withapertureCount" INTEGER NOT NULL,
    "withaperturemain" TEXT NOT NULL,
    "withaperturemainCount" INTEGER NOT NULL,
    CONSTRAINT "Compose_codeId_fkey" FOREIGN KEY ("codeId") REFERENCES "Code" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
